//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedCentr.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests_for_attachment
    {
        public int Requests_for_attachment_Id { get; set; }
        public System.DateTime DateOfCreationg { get; set; }
        public Nullable<System.DateTime> DateOfTreatments { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string QueryStatus { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
